### ISSUE TITLE
token doesn't work

### ISSUE THREAD

**Issue by itslijohnny** [abrochard/emacs-habitica#10]
I am currently using spacemacs. it works perfectly with the emacs-habitica. However, when I put (setq habitica-uid "xxx") (setq habitica-token "xxxxx") in .spacemacs it ask me to type in username and password again. When i type in the username and password it says "wrong type argument"...

**Comment by abrochard** [comment]
Hmm, I don't use spacemacs at all, but I can try taking a look.
Just to make sure I understand:

- if you don't set uid and token, and just call `habitica-tasks`, it prompts for username and password and works normally?
- if you do set your uid and token and call `habitica-tasks`, it still prompts for username and password, but fails with a "wrong type argument" error?

The second case is weird because I specifically wrote
```
(if (or (not habitica-uid) (not habitica-token))
  (call-interactively 'habitica-login))
```
in the `habitica-tasks` function, so if they are both set properly you should never be prompted.

**Comment by itslijohnny** [comment]
sorry about my language, but yes you were right. BTW, did you do any modification today? the login problem solved. but the interface shows:

` * Habits :habit:`
`** TODO xxxx(my fist babit): `
`   :PROPERTIES: `
`   :ID:       26f74ee4-1483-.....(i delete the rest number, in case it is sensitive) `
`   :END:`

**Comment by abrochard** [comment]
The login worked? That's weird. I didn't change anything. I also can't reproduce the problem.

And yes it's normal to see that id. I use org-mode properties to store the task id for when I'm calling the API. It's not sensitive. Normally, `org-content` gets called and hides it away.

**Comment by itslijohnny** [comment]
i mean it only showed my first TODO and kind of showing the id. Before the login didn't work. it was show the full list. I will try delete .spacemacs and restore it to see the problem.

**Comment by itslijohnny** [comment]
I delete the .spacesmacs and setup spacesmacs again and it worked. I think there must be some conflict with other packages.

**Comment by abrochard** [comment]
oh wow. I know really nothing about spacemacs. Where do you think it could be coming from?

**Comment by itslijohnny** [comment]
i think there must be some conflicts with org-mode configuration.As long as I uncommon org in  "dotspacemacs-configuration-layers"  it has the problem. it shows "Symbol's function definition is void: org-link-types."  But once I put (setq org-directory "~/xxxxxx/l") in .spacemacs file the habitica interface shows, but only showed my first TODO .

**Comment by itslijohnny** [comment]
I wish I know more about programming. I find out that in terminal everything works just fine. I really have no idea. Hope the information can help you find out the problem. Thanks for the response and patience.

**Comment by abrochard** [comment]
No worries. Give me a bit of time and I'll install spacemacs and try it out myself.

**Comment by itslijohnny** [comment]
Thanks a lot. Here's some update. I tried delete everything and install back several times in the weekend. Some how it worked. I suspect [emoji layer]( http://spacemacs.org/layers/+fun/emoji/README.html) is the reason. because this is the one layer I didn't install. And since I don't know how I make everything works, I will not try to install emoji layer again, in case something wrong.

**Comment by abrochard** [comment]
Still trying to work my way through spacemacs.
Have you seen those two issues in spacemacs?

https://github.com/syl20bnr/spacemacs/issues/8334
https://github.com/syl20bnr/spacemacs/issues/8074

Can you try to call `package-initialize` in init.el before the org-mode code gets evaluated? It seems to be a fix for a few users.

**Comment by itslijohnny** [comment]
I'm now sure [emoji](http://spacemacs.org/layers/+fun/emoji/README.html) layer cause the problem. I installed emoji and it has the problem. I delete the emoji and everything works just fine.
