### ISSUE TITLE
Show checklists for tasks that have them (feature request)

### ISSUE THREAD

**Issue by real-milos** [abrochard/emacs-habitica#8]
Hello.

First of all, thanks for the amazing package, your work is very much appreciated.

There is one thing I did not find in your `roadmap.org` file, and that is displaying checklists for tasks that have them assigned. It would be really cool to display the lists and also to have the ability to toggle their items in org-mode style (`C-c C-c`).

A quick mockup to get a feeling for what I have in mind:

![a thousand words](https://cloud.githubusercontent.com/assets/9453554/21641096/f1ea1944-d279-11e6-98d4-046ce4f3e535.png)

Thanks for your consideration.

**Comment by abrochard** [comment]
Thank you very much for the feedback!
I am very happy that you like the extension.
And you are right, I completely missed the checklist feature. I am going to add it now to the roadmap and it shall be the next thing I work on.
Feel free to create another issue if something else is missing,
Best,
Adrien

**Comment by abrochard** [comment]
Just merged my dev branch into master with code for checklist support.
https://github.com/abrochard/emacs-habitica/pull/9/files

You should get it at next MELPA build if that's how you installed it.

I added the functions:

- ["Score a checklist item" habitica-score-checklist-item]
- ["Add a checklist item" habitica-add-item-to-checklist]
- ["Rename a checklist item" habitica-rename-item-on-checklist]
- ["Delete a checklist item" habitica-delete-item-from-checklist]

And bounded habitica-score-checklist-item to `C-x t c`
Let me know if this is what you had in mind.
